-- MySQL Script generated by MySQL Workbench
-- Tue Aug  5 19:42:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smts_baza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smts_baza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smts_baza` ;
USE `smts_baza` ;

-- -----------------------------------------------------
-- Table `smts_baza`.`Misija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Misija` (
  `misija_id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(255) NOT NULL,
  `datum_pocetka` DATE NULL DEFAULT NULL,
  `datum_kraja` DATE NULL DEFAULT NULL,
  `cilj_misije` TEXT NULL DEFAULT NULL,
  `status` ENUM('Aktivna', 'Završena', 'Planirana') NULL DEFAULT NULL,
  PRIMARY KEY (`misija_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Tip_Satelita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Tip_Satelita` (
  `tip_id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv_tipa` VARCHAR(100) NOT NULL,
  `opis_tipa` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`tip_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Satelit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Satelit` (
  `satelit_id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(255) NOT NULL,
  `zemlja_proizvodnje` VARCHAR(100) NULL DEFAULT NULL,
  `masa_kg` INT(11) NULL DEFAULT NULL,
  `misija_id` INT(11) NULL DEFAULT NULL,
  `tip_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`satelit_id`),
  INDEX `misija_id` (`misija_id` ASC) VISIBLE,
  INDEX `tip_id` (`tip_id` ASC) VISIBLE,
  CONSTRAINT `Satelit_ibfk_1`
    FOREIGN KEY (`misija_id`)
    REFERENCES `smts_baza`.`Misija` (`misija_id`),
  CONSTRAINT `Satelit_ibfk_2`
    FOREIGN KEY (`tip_id`)
    REFERENCES `smts_baza`.`Tip_Satelita` (`tip_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Zemaljska_Stanica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Zemaljska_Stanica` (
  `stanica_id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(255) NOT NULL,
  `lokacija` VARCHAR(255) NULL DEFAULT NULL,
  `zemlja_stanice` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`stanica_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Komunikacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Komunikacija` (
  `satelit_id` INT(11) NOT NULL,
  `stanica_id` INT(11) NOT NULL,
  `datum_komunikacije` DATE NOT NULL,
  `tip_komunikacije` VARCHAR(100) NULL DEFAULT NULL,
  INDEX `satelit_id` (`satelit_id` ASC) VISIBLE,
  INDEX `stanica_id` (`stanica_id` ASC) VISIBLE,
  UNIQUE INDEX `komunikacija_unique` (`satelit_id` ASC, `stanica_id` ASC, `datum_komunikacije` ASC) VISIBLE,
  CONSTRAINT `Komunikacija_ibfk_1`
    FOREIGN KEY (`satelit_id`)
    REFERENCES `smts_baza`.`Satelit` (`satelit_id`),
  CONSTRAINT `Komunikacija_ibfk_2`
    FOREIGN KEY (`stanica_id`)
    REFERENCES `smts_baza`.`Zemaljska_Stanica` (`stanica_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Raketa_Nosac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Raketa_Nosac` (
  `raketa_id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(255) NOT NULL,
  `proizvodjac` VARCHAR(100) NULL DEFAULT NULL,
  `kapacitet_tovar_kg` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`raketa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Mjesto_Lansiranja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Mjesto_Lansiranja` (
  `mjesto_id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(255) NOT NULL,
  `država` VARCHAR(100) NULL DEFAULT NULL,
  `geografska_duzina` DECIMAL(9,6) NULL DEFAULT NULL,
  `geografska_sirina` DECIMAL(9,6) NULL DEFAULT NULL,
  PRIMARY KEY (`mjesto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Lansiranje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Lansiranje` (
  `lansiranje_id` INT(11) NOT NULL AUTO_INCREMENT,
  `datum_lansiranja` DATE NULL DEFAULT NULL,
  `raketa_id` INT(11) NULL DEFAULT NULL,
  `misija_id` INT(11) NULL DEFAULT NULL,
  `satelit_id` INT(11) NULL DEFAULT NULL,
  `mjesto_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`lansiranje_id`),
  INDEX `raketa_id` (`raketa_id` ASC) VISIBLE,
  INDEX `misija_id` (`misija_id` ASC) VISIBLE,
  INDEX `satelit_id` (`satelit_id` ASC) VISIBLE,
  INDEX `mjesto_id` (`mjesto_id` ASC) VISIBLE,
  CONSTRAINT `Lansiranje_ibfk_1`
    FOREIGN KEY (`raketa_id`)
    REFERENCES `smts_baza`.`Raketa_Nosac` (`raketa_id`),
  CONSTRAINT `Lansiranje_ibfk_2`
    FOREIGN KEY (`misija_id`)
    REFERENCES `smts_baza`.`Misija` (`misija_id`),
  CONSTRAINT `Lansiranje_ibfk_3`
    FOREIGN KEY (`satelit_id`)
    REFERENCES `smts_baza`.`Satelit` (`satelit_id`),
  CONSTRAINT `Lansiranje_ibfk_4`
    FOREIGN KEY (`mjesto_id`)
    REFERENCES `smts_baza`.`Mjesto_Lansiranja` (`mjesto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Zemlja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Zemlja` (
  `zemlja_id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv_zemlje` VARCHAR(100) NOT NULL,
  `kontinent` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`zemlja_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Operater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Operater` (
  `operater_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ime_operatera` VARCHAR(255) NOT NULL,
  `tip_organizacije` VARCHAR(100) NULL DEFAULT NULL,
  `zemlja_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`operater_id`),
  INDEX `zemlja_id` (`zemlja_id` ASC) VISIBLE,
  CONSTRAINT `Operater_ibfk_1`
    FOREIGN KEY (`zemlja_id`)
    REFERENCES `smts_baza`.`Zemlja` (`zemlja_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Orbita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Orbita` (
  `orbita_id` INT(11) NOT NULL AUTO_INCREMENT,
  `visina_km` INT(11) NULL DEFAULT NULL,
  `inklinacija_stepeni` DECIMAL(5,2) NULL DEFAULT NULL,
  `period_min` INT(11) NULL DEFAULT NULL,
  `satelit_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`orbita_id`),
  INDEX `satelit_id` (`satelit_id` ASC) VISIBLE,
  CONSTRAINT `Orbita_ibfk_1`
    FOREIGN KEY (`satelit_id`)
    REFERENCES `smts_baza`.`Satelit` (`satelit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Uloga_Operatera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Uloga_Operatera` (
  `uloga_id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv_uloge` VARCHAR(100) NOT NULL,
  `opis_uloge` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`uloga_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Sudjelovanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Sudjelovanje` (
  `misija_id` INT(11) NULL DEFAULT NULL,
  `operater_id` INT(11) NULL DEFAULT NULL,
  `uloga_id` INT(11) NULL DEFAULT NULL,
  INDEX `misija_id` (`misija_id` ASC) VISIBLE,
  INDEX `operater_id` (`operater_id` ASC) VISIBLE,
  INDEX `uloga_id` (`uloga_id` ASC) VISIBLE,
  UNIQUE INDEX `sudjelovanje_unique` (`misija_id` ASC, `operater_id` ASC) VISIBLE,
  CONSTRAINT `Sudjelovanje_ibfk_1`
    FOREIGN KEY (`misija_id`)
    REFERENCES `smts_baza`.`Misija` (`misija_id`),
  CONSTRAINT `Sudjelovanje_ibfk_2`
    FOREIGN KEY (`operater_id`)
    REFERENCES `smts_baza`.`Operater` (`operater_id`),
  CONSTRAINT `Sudjelovanje_ibfk_3`
    FOREIGN KEY (`uloga_id`)
    REFERENCES `smts_baza`.`Uloga_Operatera` (`uloga_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `smts_baza`.`Zemlja_u_Misiji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smts_baza`.`Zemlja_u_Misiji` (
  `misija_id` INT(11) NOT NULL,
  `zemlja_id` INT(11) NOT NULL,
  `doprinos` VARCHAR(100) NULL DEFAULT NULL,
  INDEX `misija_id` (`misija_id` ASC) VISIBLE,
  INDEX `zemlja_id` (`zemlja_id` ASC) VISIBLE,
  UNIQUE INDEX `zum_unique` (`misija_id` ASC, `zemlja_id` ASC) VISIBLE,
  CONSTRAINT `Zemlja_u_Misiji_ibfk_1`
    FOREIGN KEY (`misija_id`)
    REFERENCES `smts_baza`.`Misija` (`misija_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Zemlja_u_Misiji_ibfk_2`
    FOREIGN KEY (`zemlja_id`)
    REFERENCES `smts_baza`.`Zemlja` (`zemlja_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
